# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crud.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'crud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncrud.proto\x12\x04\x63rud\" \n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x14\n\x06ItemId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa3\x01\n\x0b\x43RUDService\x12$\n\x06\x43reate\x12\n.crud.Item\x1a\x0e.crud.Response\x12 \n\x04Read\x12\x0c.crud.ItemId\x1a\n.crud.Item\x12$\n\x06Update\x12\n.crud.Item\x1a\x0e.crud.Response\x12&\n\x06\x44\x65lete\x12\x0c.crud.ItemId\x1a\x0e.crud.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=20
  _globals['_ITEM']._serialized_end=52
  _globals['_ITEMID']._serialized_start=54
  _globals['_ITEMID']._serialized_end=74
  _globals['_RESPONSE']._serialized_start=76
  _globals['_RESPONSE']._serialized_end=103
  _globals['_CRUDSERVICE']._serialized_start=106
  _globals['_CRUDSERVICE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
